In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

In [ ]:
data = pd.read_csv('data/SPX_vol_surface.csv')
max_ivol = data.impl_volatility.max()

unique_dates = data.date.unique()
unique_deltas = data.delta.unique()
unique_tenors = data.days.unique()

num_dates = unique_dates.shape[0]
num_deltas = unique_deltas.shape[0]
num_tenors = unique_tenors.shape[0]


# Shape: (num_dates, num_tenors, num_deltas)
vol_surface_matrix = data.set_index(
    ["date", "days", "delta"]).impl_volatility.unstack().values.reshape(
    num_dates, num_tenors, num_deltas)

vol_surface_matrix /= (255/max_ivol)

dates = pd.to_datetime(unique_dates, format='%Y%m%d')


midx = pd.MultiIndex.from_product([dates, unique_deltas])
data = pd.DataFrame(index = midx, columns = unique_tenors, dtype='float')
for i in range(len(dates)):
    data.loc[dates[i]] = vol_surface_matrix.squeeze()[i].T

In [2]:
data = pd.read_csv('data/SPX_vol_surface_FULL.csv')

In [3]:
data.head(10)

,secid,date,days,delta,impl_volatility,impl_strike,impl_premium,dispersion,cp_flag,cusip,ticker,index_flag
0,108105,19960104,10,-90,NaN,0.0,0.0,NaN,P,64881510,SPX,1
1,108105,19960104,10,-85,NaN,0.0,0.0,NaN,P,64881510,SPX,1
2,108105,19960104,10,-80,NaN,0.0,0.0,NaN,P,64881510,SPX,1
3,108105,19960104,10,-75,NaN,0.0,0.0,NaN,P,64881510,SPX,1
4,108105,19960104,10,-70,NaN,0.0,0.0,NaN,P,64881510,SPX,1
5,108105,19960104,10,-65,NaN,0.0,0.0,NaN,P,64881510,SPX,1
6,108105,19960104,10,-60,NaN,0.0,0.0,NaN,P,64881510,SPX,1
7,108105,19960104,10,-55,NaN,0.0,0.0,NaN,P,64881510,SPX,1
8,108105,19960104,10,-50,NaN,0.0,0.0,NaN,P,64881510,SPX,1
9,108105,19960104,10,-45,NaN,0.0,0.0,NaN,P,64881510,SPX,1

In [4]:
data = data.dropna()

In [5]:
data

,secid,date,days,delta,impl_volatility,impl_strike,impl_premium,dispersion,cp_flag,cusip,ticker,index_flag
34,108105,19960104,30,-90,0.138704,652.5124,34.12913,0.007301,P,64881510,SPX,1
35,108105,19960104,30,-85,0.137368,645.8368,28.19517,0.007203,P,64881510,SPX,1
36,108105,19960104,30,-80,0.135625,640.5763,23.73218,0.007088,P,64881510,SPX,1
37,108105,19960104,30,-75,0.132932,636.0494,20.03727,0.007155,P,64881510,SPX,1
38,108105,19960104,30,-70,0.128539,631.9539,16.76515,0.006979,P,64881510,SPX,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2447825,108105,20211231,730,70,0.250166,4117.9040,963.06740,0.021641,C,64881510,SPX,1
2447826,108105,20211231,730,75,0.265997,3860.0170,1151.87500,0.025721,C,64881510,SPX,1
2447827,108105,20211231,730,80,0.283967,3558.3270,1383.19300,0.031471,C,64881510,SPX,1
2447828,108105,20211231,730,85,0.303781,3196.2870,1672.48600,0.039406,C,64881510,SPX,1
2447829,108105,20211231,730,90,0.325091,2739.7030,2053.89500,0.049608,C,64881510,SPX,1

In [6]:
data

,secid,date,days,delta,impl_volatility,impl_strike,impl_premium,dispersion,cp_flag,cusip,ticker,index_flag
34,108105,19960104,30,-90,0.138704,652.5124,34.12913,0.007301,P,64881510,SPX,1
35,108105,19960104,30,-85,0.137368,645.8368,28.19517,0.007203,P,64881510,SPX,1
36,108105,19960104,30,-80,0.135625,640.5763,23.73218,0.007088,P,64881510,SPX,1
37,108105,19960104,30,-75,0.132932,636.0494,20.03727,0.007155,P,64881510,SPX,1
38,108105,19960104,30,-70,0.128539,631.9539,16.76515,0.006979,P,64881510,SPX,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2447825,108105,20211231,730,70,0.250166,4117.9040,963.06740,0.021641,C,64881510,SPX,1
2447826,108105,20211231,730,75,0.265997,3860.0170,1151.87500,0.025721,C,64881510,SPX,1
2447827,108105,20211231,730,80,0.283967,3558.3270,1383.19300,0.031471,C,64881510,SPX,1
2447828,108105,20211231,730,85,0.303781,3196.2870,1672.48600,0.039406,C,64881510,SPX,1
2447829,108105,20211231,730,90,0.325091,2739.7030,2053.89500,0.049608,C,64881510,SPX,1